name: GitHub Actions CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  ci:
    runs-on: macos-12
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - run: contrib/tests.sh
        env:
          ZSH_DOTFILES_PREP_CI: 1
          ZSH_DOTFILES_PREP_DEBUG: 1
          ZSH_DOTFILES_PREP_GITHUB_USER: bossjones

      - run: brew config

      - run: brew cleanup

      - run: brew doctor

